### ISSUE TITLE
"non-actioned" events

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/context-mod#41]
I'd like to see a page with the results for every check that's run as well as a button to rerun the check on that post/comment.

**Comment by FoxxMD** [comment]
It's a good idea but the blocking issue for this is scaling. For low-volume subreddits this would be a non-issue but CM runs on subreddits which do checks daily across 13k-30k activities. It's not feasible to hold all of those results in memory (the default cache/store configuration). Redis would work but still doesn't scale across multiple days...I've got one subreddit that's done 9.6 million activities in the last month.

Issues I see with this and some off-the-cuff remedies:

### Scaling 

How to store results in a way that works from 10 to 10k activities per day?

* user-configurable tailing max limit IE similar to log limit, only retain last X number of activities per subreddit
* results are already stored as plain objects/arrays/strings (works with redis) but could probably be compressed further to save space
* user-configurable result store trigger IE only store if at least X rules triggered or rule X is triggered
  * this could get complicated...how to keep it simple?

### Finding useful information

At lower volumes it should be easy to find the result you are looking for. But at higher volumes will need to be able to filter results or else it'll be as useless as fast logging for high-volume subreddits

* Filter by
  * permalink
  * title/content (not sure this is good to store since content could be very long)
  * author
  * activity type (comment/submission)
  * check
  * rule
  * action

Additionally, may be prudent to fold **all results** to this change. So actioned/non-actioned alike. Then actioned can just be another filter (maybe still store separately so tailing limit doesn't apply?)

### Retaining useful information

A user may want to retain a certain result but if the tailing limit is low or subreddit is high volume it could potentially be dropped quickly. Will need a way to store and retrieve user-defined results.

**Comment by FoxxMD** [comment]
Implemented in [0.11.0](https://github.com/FoxxMD/context-mod/releases/tag/0.11.0)
