### ISSUE TITLE
"Actioned events" is empty all the time

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/context-mod#45]
Seems that actioned events max kept is based on total events not actioned ones meaning after x events the "actions events" page is cleared.

**Comment by FoxxMD** [comment]
It is based on actioned events. From `SubredditResources.ts`

```ts
async addActionedEvent(ae: ActionedEvent) {
    const events = await this.cache.wrap(`actionedEvents-${this.subreddit.display_name}`, () => []) as ActionedEvent[];
    events.unshift(ae);
    await this.cache.set(`actionedEvents-${this.subreddit.display_name}`, events.slice(0, this.actionedEventsMax), {ttl: 0});
}
```

This behavior may be a result of the default cache store using [lru-cache](https://github.com/isaacs/node-lru-cache). The default max store size is 500 keys -- if there are many things being cached it may be that the KV for actioned events is being dropped because it is too infrequently set. Trying to verify this now...

**Comment by OmgImAlexis** [comment]
@FoxxMD you should be storing two caches, one for all events and one for actioned. This way the last 500 actioned events are also cached. Personally I'd like to enable a mode to store all actioned ones forever. I have more than enough memory in my server to handle this. (128GB)

**Comment by FoxxMD** [comment]
I'm closing this as it should be solved by switching to a database. If anyone has this issue still I can re-open.
