### ISSUE TITLE
allow nuking a user

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/context-mod#47]
It'd be nice to not only be able to check a permalink but a whole user. This would be great for new spam as we could add the new spam rule and then run it against that whole account removing all their posts.

**Comment by FoxxMD** [comment]
I've given this a ton of thought since you initially suggested it. I've kind of been waiting to see if CM would evolve to a point where this functionality didn't feel as destructive -- or potentially abusive -- but it really hasn't mellowed out, for me.

A core principle for the design of CM I've tried to abide by is **don't build tools that explicitly enable abuse.** While most of the functionality for CM _could_ be used for abuse none of it is provided as an abuse "button" that makes it as simple as one line in the config to abuse the bot and moderator actions. 

One of the factor for preventing that kind of design has been making the majority of CM's actions reactive to **the current activity only.** That is, if a user posts/comments and that activity breaks the rules then CM only acts on that one activity (and the user, at that time).

The ability to nuke all of a user's history in a subreddit with one action in CM strays too far into the territory of an "abuse button" for me by going against the design of "only action the current activity" with a destructive action. My main concerns, in this context, with nuking a user are that:

* a bad actor could retroactively remove all opposing views/conversations in an entire thread or across the subreddit with one CM action
* they could also create a chilling effect or "break" the spirit of opposing users by removing all of the hard work they have put into conversation by making all of that content inaccessible to users browsing the subreddit.

While users can still be censored with CM in its current state it does not enable retroactive censorship and reshaping the conversation of past threads or entire subreddit histories.

Additionally, this would be an extremely bad action to have done accidentally. Since CM's behavior is not necessarily dictated by expert users, a moderator with less knowledge could "accidentally" use this on the wrong user due to rule misconfiguration. There is no way to undo that mistake unless I also implemented a "de-nuke" action but that would basically just be there to help undo this mess...which I can avoid by not implementing it in the first place.

___

While I totally understand the usefulness of this in the hands of good mods, such as nuke old spammers/abusers, it's too ripe for abuse and accidental use, IMO.
